mongo:
  image: mongo
  command: --smallfiles
  ports:
    - "27017:27017"
  volumes:
    - ./data:/data/db
api_ci:
  build: "."
  command: node server.js
  ports:
    - "3000"
  environment:
    - ENV=test
    - PORT=3000
  links:
    - mongo
