mongo:
  image: mongo
  command: --smallfiles
  ports:
    - "27017:27017"
  volumes:
    - ./data:/data/db
api1:
  build: "."
  container_name: "api1_1"
  command: node server.js
  ports:
    - "3000"
  environment:
    - ENV=production
    - PORT=3000
  links:
    - mongo
api2:
  build: "."
  container_name: "api2_1"
  command: node server.js
  ports:
    - "3000"
  environment:
    - ENV=production
    - PORT=3000
  links:
    - mongo
api3:
  container_name: "api3_1"
  build: "."
  command: node server.js
  ports:
    - "3000"
  environment:
    - ENV=production
    - PORT=3000
  links:
    - mongo
nginx:
  build: "./docker/nginx"
  links:
    - api1:api1
    - api2:api2
    - api3:api3
  ports:
    - "9000:9000"
