mongo:
  image: mongo
  command: --smallfiles
  ports:
    - "27017:27017"
  volumes:
    - ./data:/data/db
api_dev:
  build: "."
  command: ./node_modules/.bin/nodemon -L --debug=5858 ./server.js --color=always
  ports:
    - "3000:3000"
    - "5858:5858"
  volumes:
    - ./:/api:z
  links:
    - mongo
